<a href="https://colab.research.google.com/github/nayoonchoi00/PyTorch-DL/blob/main/01_%ED%85%90%EC%84%9C%EB%A5%BC_%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94_%EB%8B%A4%EC%96%91%ED%95%9C%EB%B0%A9%EB%B2%95_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## torch import


In [1]:
import torch
import numpy as np

# version 체크
print(torch.__version__)

2.4.0+cu121


## 기본 텐서 생성


In [2]:
# 샘플 numpy array 생성
arr = np.arange(0, 5)
print(arr)

[0 1 2 3 4]


### `torch.from_numpy()`

- numpy array 로부터 생성. **sharing** 하므로 numpy array의 요소가 변경되면 tensor로 같이 변경됩니다


In [3]:
t1 = torch.from_numpy(arr)
print(t1)  # 출력
print(t1.dtype)  # dtype은 데이터 타입
print(t1.type())  # type()은 텐서의 타입
print(type(t1))  # t1 변수 자체의 타입

tensor([0, 1, 2, 3, 4])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


### `torch.as_tensor()`

- numpy array 로부터 생성. **sharing** 하므로 numpy array의 요소가 변경되면 tensor로 같이 변경됩니다


In [4]:
t2 = torch.as_tensor(arr)
print(t2)  # 출력
print(t2.dtype)  # dtype은 데이터 타입
print(t2.type())  # type()은 텐서의 타입
print(type(t2))  # t2 변수 자체의 타입

tensor([0, 1, 2, 3, 4])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


### `torch.tensor()`

- numpy array 로부터 생성. **copying** 하므로 numpy array의 요소가 변경에 영향을 받지 않습니다.


In [5]:
t3 = torch.tensor(arr)
print(t3)  # 출력
print(t3.dtype)  # dtype은 데이터 타입
print(t3.type())  # type()은 텐서의 타입
print(type(t3))  # t3 변수 자체의 타입

tensor([0, 1, 2, 3, 4])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


## Zeros, Ones


### `torch.zeros()`

- 0으로 채워진 tensor를 생성합니다.
- dtype을 직접 지정하는 것이 바람직합니다.


In [6]:
zeros = torch.zeros(3, 5, dtype=torch.int32)
print(zeros)
print(zeros.dtype)
print(zeros.type())

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)
torch.int32
torch.IntTensor


### `torch.ones()`

- 1로 채워진 tensor를 생성합니다.
- 역시 dtype을 직접 지정하는 것이 바람직합니다.


In [7]:
ones = torch.ones(2, 3, dtype=torch.int64)
print(ones)
print(ones.dtype)
print(ones.type())

tensor([[1, 1, 1],
        [1, 1, 1]])
torch.int64
torch.LongTensor


### Tensors from ranges

<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.


## 범위로 생성


### `torch.arange(start, end, step)`

- 지정된 범위로 tensor를 생성합니다.


In [8]:
# end만 지정
a = torch.arange(5)
print(a)
# start, end 지정
a = torch.arange(2, 6)
print(a)
# start, end, step 모두 지정
a = torch.arange(1, 10, 2)
print(a)

tensor([0, 1, 2, 3, 4])
tensor([2, 3, 4, 5])
tensor([1, 3, 5, 7, 9])


### torch.linspace(start, end, steps)

- start부터 end까지 동일 간격으로 생성합니다. steps 지정시 steps 갯수만큼 생성합니다. (미지정시 100개 생성)


In [11]:
# start, stop 지정 ()
b = torch.linspace(2, 10,10)
#2~10 사이 동일한 간격으로.
print(b)
print(b.size(0))
print("===" * 20)
# start, stop, step 모두 지정
b = torch.linspace(2, 10, 5)
print(b)

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])
10
tensor([ 2.,  4.,  6.,  8., 10.])


## tensor의 타입 변경: type()

- tensor의 dtype을 변경하기 위해서는 type() 함수를 사용합니다. type()함수의 인자로 변경할 tensor의 타입을 지정합니다.


In [12]:
aa = torch.arange(10, dtype=torch.int32)
print(aa)
print(aa.type())

print("===" * 10)
# tensor의 타입 변경
bb = aa.type(torch.int64)
print(bb)
print(bb.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
torch.IntTensor
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


## 랜덤 tensor 생성

- `torch.rand()`: [0, 1) 분포 안에서 랜덤한 tensor를 생성합니다.
- `torch.randn()`: **standard normal** 분포 안에서 랜덤한 tensor를 생성합니다.
- `torch.randint()`: 정수로 채워진 랜덤한 tensor를 생성합니다.


In [13]:
# random 생성 범위: 0 ~ 1
rd1 = torch.rand(2, 3)
print(rd1)

tensor([[0.2466, 0.1656, 0.2105],
        [0.6935, 0.4442, 0.7428]])


In [14]:
# random 생성 범위: standard normal
rd2 = torch.randn(2, 3)
print(rd2)

tensor([[-2.4134, -0.2357,  0.5262],
        [-0.0972, -0.2254, -0.3718]])


In [18]:
# randint 생성시 low, high, size를 지정한 경우
rd3 = torch.randint(low=1, high=10, size=(2, 3))
print(rd3)

tensor([[8, 2, 2],
        [1, 9, 3]])


`torch.manual_seed()`: 난수 생성시 시드의 고정


In [19]:
# manual_seed를 고정시 고정한 cell의 난수 생성은 매번 동일한 값을 생성
torch.manual_seed(0)
#seed 안에 들어가는 값은 큰 상관은 없음.
rd4 = torch.randint(low=1, high=100, size=(2, 3))
print(rd4)

tensor([[99, 19, 57],
        [70, 53, 70]])


## like로 tensor 생성

- 텐서 생성 함수에서 `_like()`가 뒤에 붙는 함수를 종종 볼 수 있습니다.
- `_like()`가 붙은 이름의 함수는 `_like()` 안에 넣어주는 tensor의 shape와 동일한 tensor를 생성합니다.

**\_like() 함수 목록**

- `torch.rand_like()`
- `torch.randn_like()`
- `torch.randint_like()`
- `torch.ones_like()`
- `torch.zeros_like()`


In [20]:
x = torch.tensor([[1, 3, 5], [7, 9, 11]], dtype=torch.float32)
print(x)
print(x.type())

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.]])
torch.FloatTensor


In [21]:
# [0, 1)
like1 = torch.rand_like(x)
print(like1)
print(like1.type())

tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])
torch.FloatTensor


In [22]:
# standard normal
like2 = torch.randn_like(x)
print(like2)
print(like2.type())

tensor([[ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])
torch.FloatTensor


In [23]:
# int range
like3 = torch.randint_like(x, low=1, high=100)
print(like3)
print(like3.type())

tensor([[90., 24., 98.],
        [99., 43., 10.]])
torch.FloatTensor


In [24]:
# zeros
like4 = torch.zeros_like(x)
print(like4)
print(like4.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [25]:
# ones
like5 = torch.ones_like(x)
print(like5)
print(like5.type())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


## tensor의 shape 확인 및 변경


In [26]:
x = torch.tensor([[1, 3, 5], [7, 9, 11]], dtype=torch.float32)
print(x)

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.]])


### shape 확인


In [27]:
print(x.shape)
print(x.shape[0])
print(x.shape[1])

torch.Size([2, 3])
2
3


In [28]:
print(x.size())
print(x.size(0))
print(x.size(1))

torch.Size([2, 3])
2
3


### shape 변경


`view()`와 `reshape()` 모두 사용가능합니다.


In [29]:
x = torch.tensor([[1, 3, 5], [7, 9, 11]], dtype=torch.float32)
print(x)
print(x.shape)

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.]])
torch.Size([2, 3])


In [30]:
print(x)
# view()로 shape 변경
print(x.view(3, 2))

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.]])
tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


In [31]:
x.size()

torch.Size([2, 3])

In [32]:
# view
#마이너스= 와일드카드. 뒤에는 1로 고정하고 앞에 있는 마이너스 값에 알아서 넣어라~
#단, 나누어 떨어져야 함.
x.view(-1, 1)

tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])

In [34]:
x.view(-1,1).size()

torch.Size([6, 1])

In [35]:
# reshape
x.reshape(-1, 1)

tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])

In [36]:
# view
x.view(3, -1)

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])

In [38]:
# reshape
x.reshape(3, -1)

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])